### ISSUE TITLE
Best Practice: Add a config file containing Client and extension IDs

### ISSUE THREAD

**Issue by saiflakhani** [schezfaz/spot#7]
Still haven't found a way to load another js file into background.js
Once this is achieved, add the file to .gitignore to prevent clashing IDs

**Comment by schezfaz** [comment]
Also, lets think long term, when we need to publish this extension to the Google Play Store. What would be the ideal way to do that, without depending on these credentials from the user side? I believe there are a couple of Spotify extensions already available, lets analyse that to see how we can implement this.

**Comment by saiflakhani** [comment]
Okay so when we publish to the chrome store, our extension ID will be static.
Then, in your spotify app dashboard, you change the redirect URI to the newly given, unchangeable extension ID. Done, right?
Am I missing something?
